name: Publish to Hangar
on:
  push:
    branches:
      - master

jobs:
  publish:
    if: github.repository_owner == 'AndrewDragonCh'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Publish
        run: ./gradlew build publishPluginPublicationToHangar --stacktrace
        env:
          HANGAR_TOKEN: ${{ secrets.HANGAR_API_TOKEN }}