name: Publish
on:
  push:
    branches:
      - master

jobs:
  publish:
    if: github.repository_owner == 'AndrewDragonCh'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Publish to Hangar
        run: ./gradlew build publishPluginPublicationToHangar --stacktrace
        env:
          HANGAR_API_TOKEN: ${{ secrets.HANGAR_API_TOKEN }}
      - name: Publish to Modrinth and GitHub
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: DisablePortals
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          version: 0.0.4
          version-type: beta

          loaders: paper
          game-versions: | 
            >=1.20
          java: 17